name: build
on:
  pull_request:
  push:
    tags:
      - "*"
      - "!v*"
  release:
    types:
      - published
jobs:
  package:
    runs-on: ubuntu-latest
    container: emqx/build-env:erl23.2.7.2-emqx-2-ubuntu20.04
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: |
          ls -al _build/emqtt_bench/rel/emqtt_bench/bin
          ./_build/emqtt_bench/rel/emqtt_bench/bin/emqtt_bench

  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/emqtt-bench
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/build-push-action@v2
        if: github.event_name != 'release'
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
